apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.7.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: streama
  name: streama
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: streama
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: streama
    spec:
      containers:
      - env:
        - name: ACTIVE_PROFILE
          value: mysql
        - name: MYSQL_DB
          value: streama
        - name: MYSQL_HOST
          value: mysql
        - name: MYSQL_PASSWORD
          value: password
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_USER
          value: streama
          #        image: fashaikh7/streama-server:latest
        image: fawadaksregistry.azurecr.io/streamaapp/streama-server:latest
        name: streama
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.7.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: streama
  name: streama
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    io.kompose.service: streama
status:
  loadBalancer: {}  
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: streama-ingress
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: streama.6df5278a514e48f8beaa.westus2.aksapp.io
    http:
      paths:
      - backend:
          serviceName: streama
          servicePort: 8080
        path: /
 
      
      
